(load "/usr/share/cl-quicklisp/quicklisp.lisp")
(quicklisp-quickstart:install)
(ql:add-to-init-file)
(ql:quickload :clx-truetype)
(ql:quickload :xml-emitter)
(ql:quickload :dbus)
(ql:quickload :ieee-floats)
(ql:quickload :flexi-streams)
(ql:quickload :cl-xmlspam)
(ql:quickload :ironclad)
(xft:cache-fonts)
(clx-truetype:cache-fonts)
(quit)
